# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keycontent',
            options={'ordering': ['-create_time']},
        ),
    ]
