# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20161128_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
    ]
